version = "v1"

[installer]
name              = "My EKS App"
description       = "A demo app that runs on EKS."
slug              = "my-eks-app"
documentation_url = "https://docs.nuon.co/"
community_url     = "https://join.slack.com/t/nuoncommunity/shared_invite/zt-1q323vw9z-C8ztRP~HfWjZx6AXi50VRA"
logo_url          = "https://assets-global.website-files.com/62a2c1332b518a9eedc6de2f/651df2030c43865b9b16046b_Group%2048.png"
github_url        = "https://github.com/nuonco"
homepage_url      = "https://www.nuon.co/"
demo_url          = "https://www.nuon.co/"

[sandbox]
terraform_version = "1.5.4"
[sandbox.public_repo]
directory = "aws-eks"
repo = "nuonco/sandboxes"
branch = "main"

[runner]
runner_type = "aws-eks"

[[components]]
name   = "docker_image"
type = "docker_build"
dockerfile = "Dockerfile"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-eks-tutorial/components/docker-image"
branch    = "main"

[[components]]
name   = "certificate"
type = "terraform_module"
terraform_version = "1.5.3"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-eks-tutorial/components/certificate"
branch    = "main"
[[components.var]]
name  = "domain_name"
value = "introspect.{{.nuon.install.sandbox.outputs.public_domain.name}}"
[[components.var]]
name  = "zone_id"
value = "{{.nuon.install.sandbox.outputs.public_domain.zone_id}}"

[[components]]
name   = "helm_chart"
type = "helm_chart"
chart_name = "introspect"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-eks-tutorial/components/helm-chart"
branch    = "main"
[[components.value]]
name  = "image.repository"
value = "{{.nuon.components.docker_image.image.repository.uri}}"
[[components.value]]
name  = "image.tag"
value = "{{.nuon.components.docker_image.image.tag}}"
[[components.value]]
name  = "api.nlbs.public_domain_certificate"
value = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
[[components.value]]
name  = "api.nlbs.public_domain"
value = "introspect.{{.nuon.install.sandbox.outputs.public_domain.name}}"
[[components.value]]
name  = "app_id"
value = "{{.nuon.app.id}}"
[[components.value]]
name  = "org_id"
value = "{{.nuon.org.id}}"
[[components.value]]
name  = "install_id"
value = "{{.nuon.install.id}}"
[[components.value]]
name  = "vpc_id"
value = "{{.nuon.install.sandbox.outputs.vpc.id}}"
