version = "v1"

[installer]
name              = "My AWS Lambda App"
description       = "A demo AWS Lambda app."
slug              = "my-aws-lambda-app"
documentation_url = "https://docs.nuon.co/"
community_url     = "https://join.slack.com/t/nuoncommunity/shared_invite/zt-1q323vw9z-C8ztRP~HfWjZx6AXi50VRA"
logo_url          = "https://assets-global.website-files.com/62a2c1332b518a9eedc6de2f/651df2030c43865b9b16046b_Group%2048.png"
github_url        = "https://github.com/nuonco"
homepage_url      = "https://www.nuon.co/"
demo_url          = "https://www.nuon.co/"

[sandbox]
terraform_version = "1.5.4"
[sandbox.public_repo]
directory = "aws-ecs"
repo = "nuonco/sandboxes"
branch = "main"

[runner]
runner_type = "aws-ecs"

[[components]]
name   = "docker_image"
type = "docker_build"
dockerfile = "Dockerfile"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-lambda-tutorial/components/api"
branch    = "main"

[[components]]
name   = "dynamodb_table"
type = "terraform_module"
terraform_version = "1.5.3"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-lambda-tutorial/components/dynamodb-table"
branch    = "main"
[[components.var]]
name  = "name"
value = "widgets"
[[components.var]]
name  = "hash_key"
value = "ID"

[[components]]
name   = "get_function"
type = "terraform_module"
terraform_version = "1.5.3"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-lambda-tutorial/components/lambda-function"
branch    = "main"
[[components.var]]
name  = "function_name"
value = "widgets"
[[components.var]]
name  = "image_uri"
value = "{{.nuon.components.get_handler.image.repository.uri}}:{{.nuon.components.get_handler.image.tag}}"
[[components.var]]
name  = "dynamodb_table_arn"
value = "{{.nuon.components.dynamodb_table.dynamodb_table_arn}}"

[[components]]
name   = "certificate"
type = "terraform_module"
terraform_version = "1.5.3"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-lambda-tutorial/components/certificate"
branch    = "main"
[[components.var]]
name  = "domain_name"
value = "widgets.{{.nuon.install.sandbox.outputs.public_domain.name}}"
[[components.var]]
name  = "zone_id"
value = "{{.nuon.install.sandbox.outputs.public_domain.zone_id}}"

[[components]]
name   = "api_gateway"
type = "terraform_module"
terraform_version = "1.5.3"
[components.public_repo]
repo      = "nuonco/guides"
directory = "aws-lambda-tutorial/components/api-gateway"
branch    = "main"
[[components.var]]
name  = "name"
value = "widgets"
[[components.var]]
name  = "domain_name"
value = "widgets.{{.nuon.install.sandbox.outputs.public_domain.name}}"
[[components.var]]
name  = "domain_name_certificate_arn"
value = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
[[components.var]]
name  = "lambda_function_arn"
value = "{{.nuon.components.get_function.outputs.lambda_function_arn}}"
[[components.var]]
name  = "zone_id"
value = "{{.nuon.install.sandbox.outputs.public_domain.zone_id}}"
